# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: YzkxMGIwNGU0MjBiYzNkZTVlYmE1YWNjNzMyZjFlN2QzOWM1Yjk5ZTVjZjc4NTFlNmE0MTU0ZTk3OGE4ZGQzMzg1N2U3YWVjZDU1ZWI2ZjExOTA0MmQ5Zjk3NDFjNTBmMWFkN2VhNTczNzczMWM4YjJkNTU0YjRjNGNiZWY0Nzc=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
